version: '3'
services:
  web:
    build: ./web
    ports:
      - "8500:8000" #For backend server (express)
      - "3500:3000" #For frontend
  db:
    build: ./db
    ports:
      - "5500:5000" #For MySQL